const express = require('express');
const router = express.Router();
const { check, validationResult } = require('express-validator');
const jwt = require('jsonwebtoken');
const bcrypt = require('bcryptjs');
const dotenv = require('dotenv');
const authController = require('../controllers/authcontrollers');
const Shopkeeper = require('../models/shopkeeper');
const { userInfo } = require('os');
dotenv.config();
router.post('/signup', authController.post_signup);
router.post('/login', authController.post_login);
module.exports = router;
