const express = require('express');
const router = express.Router();
const { check, validationResult } = require('express-validator');
const jwt = require('jsonwebtoken');
const bcrypt = require('bcryptjs');
const dotenv = require('dotenv');
const User = require('../models/user');
const userController = require('../controllers/usercontrollers');
const { userInfo } = require('os');
dotenv.config();
router.post('/signup', userController.post_signup);
router.post('/login', userController.post_login);
module.exports = router;
